post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer TOKENHERE

{
  "title": "Made with token extractor",
  "author": "Tester",
  "url": "localhost",
  "likes": "1"
}